## 基本統計量の計算

In [1]:
# リスト型のデータを作成：[ ]で囲まれたデータ = リスト
x = [67,58,75,89,46,62,56,79,60,30,76,
64,52,66,42,81,63,59,65,77,38,86,64,70,50,
93,78,76,57,68,98,64,55,66,53,82,62,73,60,
51,49,67,56,75,85,61,58,44,79,65]

print(x)

[67, 58, 75, 89, 46, 62, 56, 79, 60, 30, 76, 64, 52, 66, 42, 81, 63, 59, 65, 77, 38, 86, 64, 70, 50, 93, 78, 76, 57, 68, 98, 64, 55, 66, 53, 82, 62, 73, 60, 51, 49, 67, 56, 75, 85, 61, 58, 44, 79, 65]


In [2]:
min(x) # 最小値

30

In [3]:
max(x) # 最大値

98

In [4]:
sum(x)  # listの各成分の和

3250

In [5]:
len(x)  # listの成分の数

50

In [6]:
sum(x)/len(x)  # 平均値の計算

65.0

In [7]:
# 統計量計算用のライブラリを読み込む
from statistics import mean, median, variance, stdev

In [8]:
mean(x)    # 平均値

65

In [9]:
median(x)  # 中央値

64.0

In [10]:
variance(x)  # 不偏分散

202.3673469387755

In [11]:
stdev(x)     # 標準偏差

14.225587753719546

In [12]:
# 数値計算用ライブラリのnumpyを読み込む
import numpy as np

In [13]:
x=np.array(x)  # list x を、numpyのlist型(numpy.array)に変更
x

array([67, 58, 75, 89, 46, 62, 56, 79, 60, 30, 76, 64, 52, 66, 42, 81, 63,
       59, 65, 77, 38, 86, 64, 70, 50, 93, 78, 76, 57, 68, 98, 64, 55, 66,
       53, 82, 62, 73, 60, 51, 49, 67, 56, 75, 85, 61, 58, 44, 79, 65])

In [14]:
x.max()

98

In [15]:
x.sum()

3250

In [16]:
x.mean()

65.0

In [17]:
# 偏差
dx = x - x.mean()
dx

array([  2.,  -7.,  10.,  24., -19.,  -3.,  -9.,  14.,  -5., -35.,  11.,
        -1., -13.,   1., -23.,  16.,  -2.,  -6.,   0.,  12., -27.,  21.,
        -1.,   5., -15.,  28.,  13.,  11.,  -8.,   3.,  33.,  -1., -10.,
         1., -12.,  17.,  -3.,   8.,  -5., -14., -16.,   2.,  -9.,  10.,
        20.,  -4.,  -7., -21.,  14.,   0.])

In [18]:
# 偏差の和
dx.sum()

0.0

In [19]:
print(x.var(ddof=0))  # 分散 (Nで割る)
print(x.var(ddof=1))  # 不偏分散 (N-1で割る)

198.32
202.3673469387755


In [20]:
# 式(1.6)に従って計算（分散＝二乗の平均-平均の二乗）
x**2  # 2乗の表記

array([4489, 3364, 5625, 7921, 2116, 3844, 3136, 6241, 3600,  900, 5776,
       4096, 2704, 4356, 1764, 6561, 3969, 3481, 4225, 5929, 1444, 7396,
       4096, 4900, 2500, 8649, 6084, 5776, 3249, 4624, 9604, 4096, 3025,
       4356, 2809, 6724, 3844, 5329, 3600, 2601, 2401, 4489, 3136, 5625,
       7225, 3721, 3364, 1936, 6241, 4225], dtype=int32)

In [21]:
np.mean(x**2)  # 2乗の平均

4423.32

In [22]:
np.mean(x)**2  # 平均の2乗

4225.0

In [23]:
var=np.mean(x**2)- np.mean(x)**2
var

198.3199999999997

In [24]:
np.sqrt(var) # 標準偏差

14.082613393827145

In [25]:
x.std()

14.082613393827156

## Pythonでの有効桁数や位取りについて

In [26]:
# 小数点以下2桁に
print(np.pi)
"{:.2f}".format(np.pi)

3.141592653589793


'3.14'

In [27]:
print("{:.2f}".format(var))

198.32


In [28]:
#文字列の中に埋め込む
text = "分散は{:.2f}です。"
text.format(var)

'分散は198.32です。'

In [29]:
# 【位取り】
text = "新潟県の人口は{:,}人です。"
niigata = 2240989
text.format(niigata)

'新潟県の人口は2,240,989人です。'